Repository decaporg/decap-cms, pull requests merged in 2020-04, with the labels that each got.

#3674 fix: support common backend configuration options from docs in ts types
  packages/netlify-cms-core/index.d.ts
Labels: type: chore

#3672 feat: add entry, collection and config prop to control widget
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
Labels: type: feature

#3678 test: fix unit tests on windows machines
  .github/workflows/nodejs.yml
  setupTestFramework.js
Labels: type: chore

#3659 Feat(widget-relation): string templates support
  jest.config.js
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
  packages/netlify-cms-core/src/lib/formatters.ts
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-lib-widgets/README.md
  packages/netlify-cms-lib-widgets/package.json
  packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js
  packages/netlify-cms-lib-widgets/src/index.ts
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  packages/netlify-cms-lib-widgets/webpack.config.js
  packages/netlify-cms-widget-relation/package.json
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
  tsconfig.json
  website/content/docs/widgets/relation.md
Labels: type: feature

#3660 fix(git-gateway): wait for identity widget to initialize
  packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
Labels: type: bug
