Repository decaporg/decap-cms, pull requests merged in 2020-07, with the labels that each got.

#3971 fix(config-schema): allow field pattern to be a regex
  packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/netlify-cms-core/src/constants/configSchema.js
Labels: type: bug

#3972 fix(cms-demo): pad days when creating test-repo date field
  dev-test/backends/test/index.html
  dev-test/index.html
Labels: type: bug

#3965 feat: added-media-dialog-component
  packages/netlify-cms-ui-default/src/MediaDialog/MediaDialog.jsx
  packages/netlify-cms-ui-default/src/MediaDialog/index.js
  packages/netlify-cms-ui-default/src/MediaDialog/story.jsx
Labels: type: feature

#3975 Fix: relation widget performance
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/actions/search.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-lib-widgets/package.json
  packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  packages/netlify-cms-widget-relation/package.json
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Labels: type: bug

#3981 feat(locale): add 'vi' locale 🇻🇳
  packages/netlify-cms-locales/README.md
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/vi/index.js
Labels: type: feature

#3990 docs(widget-relation): improve docs
  website/content/docs/widgets/relation.md
Labels: type: chore

#3989 feat(proxy-server): allow setting proxy log level
  cypress/plugins/proxy.js
  packages/netlify-cms-proxy-server/.env.example
  packages/netlify-cms-proxy-server/package.json
  packages/netlify-cms-proxy-server/src/index.ts
  packages/netlify-cms-proxy-server/src/logger.ts
  packages/netlify-cms-proxy-server/src/middlewares.ts
  packages/netlify-cms-proxy-server/src/middlewares/common/index.ts
  packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts
  packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
  yarn.lock
Labels: type: feature

#3766 feat: reorganizing the NetlifyCMS Docs navigation
  website/content/docs/add-to-your-site.md
  website/content/docs/backends-overview.md
  website/content/docs/beta-features.md
  website/content/docs/bitbucket-backend.md
  website/content/docs/collection-types.md
  website/content/docs/configuration-options.md
  website/content/docs/custom-widgets.md
  website/content/docs/deploy-preview-links.md
  website/content/docs/examples.md
  website/content/docs/external-oauth-clients.md
  website/content/docs/git-gateway-backend.md
  website/content/docs/github-backend.md
  website/content/docs/gitlab-backend.md
  website/content/docs/intro.md
  website/content/docs/open-authoring.md
  website/content/docs/releases.md
  website/content/docs/start-with-a-template.md
  website/content/docs/test-backend.md
  website/content/docs/widgets.md
  website/site.yml
  website/static/_redirects
Labels: type: chore

#3993 fix(proxy-server): change request logging level to debug
  packages/netlify-cms-proxy-server/src/middlewares/common/index.ts
Labels: type: bug

#3998 chore: fix demo site
  dev-test/backends/test/index.html
  dev-test/index.html
Labels: type: chore

#4000 fix(editor): pass back link to editor toolbar
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Editor/EditorInterface.js
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Labels: type: bug

#4001 chore: replace react-router-redux with connected-react-router
  package.json
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/bootstrap.js
  packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/NestedCollection.spec.js.snap
  packages/netlify-cms-core/src/reducers/combinedReducer.js
  packages/netlify-cms-core/src/redux/index.ts
  yarn.lock
Labels: type: chore

#4002 feat: update locale (fr)
  packages/netlify-cms-locales/src/fr/index.js
Labels: type: feature

#4019 fix(backend-github): use workflow branch when listing files to move
  packages/netlify-cms-backend-github/src/API.ts
Labels: type: bug

#4021 fix(entries-pagination): keep loading pages until entries are available
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/components/Collection/Entries/Entries.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
  yarn.lock
Labels: type: bug

#4025 fix(prop-types): check for react components via PropTypes.elementType
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js
  packages/netlify-cms-widget-object/src/ObjectControl.js
  yarn.lock
Labels: type: bug

#4020 chore: update CMS config
  website/static/admin/config.yml
Labels: type: chore

#4026 fix(widget-relation): prepend initial value search to options
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: type: bug

#4027 test(e2e): update chrome flags
  cypress/plugins/index.js
Labels: type: chore

#4028 Update Docs: Guides “nextjs”
  website/content/docs/nextjs.md
Labels: type: content

#4029 chore: fix publish action
  .github/workflows/publish.yml
Labels: type: chore

#4030 ci: fix publish script
  .github/workflows/publish.yml
  package.json
Labels: type: chore

#4055 Spelling Fix
  website/content/docs/nextjs.md
Labels: type: bug

#4057 Spelling Fix
  website/content/docs/nextjs.md
Labels: type: bug

#4035 Update Docs: Guides “nuxt”
  website/content/docs/nuxt.md
Labels: type: content

#4064 fix(backend-gitlab): use move commit action only if paths are different
  packages/netlify-cms-backend-gitlab/src/API.ts
Labels: type: bug

#4063 fix(widget-relation): handle initialization when multiple=true
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: type: bug

#4071 feat: update locale (ja)
  packages/netlify-cms-locales/src/ja/index.js
Labels: type: feature

#4073 ci(publish): switch to v1 of 2fa publish action
  .github/workflows/publish.yml
Labels: type: chore

#4060 CI: fix create release workflow
  .github/workflows/create-release.yml
Labels: type: chore

#4075 fix(widget-markdown): properly check for selection when inserting links
  cypress/integration/markdown_widget_link_spec.js
  cypress/support/commands.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/Link.js
Labels: type: bug

#4090 Update Docs: Guides “nextjs”
  website/content/docs/nextjs.md
Labels: type: content

#4091 docs: fix indentation of code blocks in lists
  website/.markdownlint.json
  website/content/docs/git-gateway-backend.md
  website/content/docs/github-backend.md
  website/netlify.toml
  website/package.json
  website/yarn.lock
Labels: type: bug
