Repository decaporg/decap-cms, pull requests merged in 2020-09, with the labels that each got.

#4243 fix(api): bitbucket implicit auth login delay
  packages/netlify-cms-lib-util/src/API.ts
Labels: type: bug

#4246 ci(publish): increase timeout
  .github/workflows/publish.yml
Labels: type: chore

#4217 feat(widget-markdown): add option mode (#4112)
  packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js
  packages/netlify-cms-widget-markdown/src/schema.js
  website/content/docs/widgets/markdown.md
Labels: type: feature

#4181 Feat: allow setting editorial workflow PR label prefix
  packages/netlify-cms-backend-bitbucket/src/API.ts
  packages/netlify-cms-backend-bitbucket/src/implementation.ts
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-github/src/API.ts
  packages/netlify-cms-backend-github/src/__tests__/API.spec.js
  packages/netlify-cms-backend-github/src/implementation.tsx
  packages/netlify-cms-backend-gitlab/src/API.ts
  packages/netlify-cms-backend-gitlab/src/implementation.ts
  packages/netlify-cms-backend-proxy/src/implementation.ts
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-lib-util/src/APIUtils.ts
  packages/netlify-cms-lib-util/src/__tests__/apiUtils.spec.js
  packages/netlify-cms-lib-util/src/implementation.ts
  packages/netlify-cms-proxy-server/src/middlewares/joi/index.ts
  packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
  packages/netlify-cms-proxy-server/src/middlewares/types.ts
  website/content/docs/backends-overview.md
Labels: type: feature

#4256 fix(widget-relation): handle optional configuration
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: type: bug

#4280 feat(docs): docs settings, group values, post summaries, weight sorting (branch updated)
  website/content/docs/add-to-your-site.md
  website/content/docs/architecture.md
  website/content/docs/backends-overview.md
  website/content/docs/beta-features.md
  website/content/docs/bitbucket-backend.md
  website/content/docs/cloudinary.md
  website/content/docs/collection-types.md
  website/content/docs/configuration-options.md
  website/content/docs/contributor-guide.md
  website/content/docs/custom-widgets.md
  website/content/docs/customization.md
  website/content/docs/deploy-preview-links.md
  website/content/docs/examples.md
  website/content/docs/external-oauth-clients.md
  website/content/docs/gatsby.md
  website/content/docs/git-gateway-backend.md
  website/content/docs/github-backend.md
  website/content/docs/gitlab-backend.md
  website/content/docs/hugo.md
  website/content/docs/intro.md
  website/content/docs/jekyll.md
  website/content/docs/middleman.md
  website/content/docs/netlify-large-media.md
  website/content/docs/nextjs.md
  website/content/docs/nuxt.md
  website/content/docs/open-authoring.md
  website/content/docs/releases.md
  website/content/docs/start-with-a-template.md
  website/content/docs/test-backend.md
  website/content/docs/uploadcare.md
  website/content/docs/widgets.md
  website/content/docs/writing-style-guide.md
  website/site.yml
  website/static/admin/config.yml
Labels: type: feature

#4282 chore: add revert failed publish command
  .github/workflows/publish.yml
  scripts/revert_publish.sh
Labels: type: chore

#4290 chore: fix misuse of the name JAMstack
  website/content/blog/netlify-cms-now-supports-gitlab-as-a-backend.md
  website/content/docs/contributor-guide.md
  website/content/docs/examples.md
  website/data/landing.yaml
  website/data/notifications.yml
Labels: type: bug

#4287 Update Docs: Intro “add-to-your-site”
  website/content/docs/add-to-your-site.md
Labels: type: content

#4332 feat(locale): add 'ko' locale 🇰🇷
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/ko/index.js
Labels: type: feature

#4319 Update Docs: Contributing “examples”
  website/content/docs/examples.md
Labels: type: content

#4326 fix(widget-relation): set initial metadata value
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: type: bug

#4279 feat(core) feat(lib-widget) Add {{dirname}} to summary and preview_path
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
  packages/netlify-cms-core/src/lib/formatters.ts
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  website/content/docs/beta-features.md
  website/content/docs/configuration-options.md
Labels: type: feature

#4328 Update Docs: Fields “custom-widgets”
  website/content/docs/custom-widgets.md
Labels: type: content
