Repository decaporg/decap-cms, pull requests merged in 2020-11, with the labels that each got.

#4397 Documentation Update
  website/content/docs/nuxt.md
Labels: type: bug

#4433 Create Docs: Guides “gridsome”
  website/content/docs/gridsome.md
Labels: type: content

#4463 fix(i18n): data is not duplicated for default value setting
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/lib/i18n.ts
  packages/netlify-cms-core/src/valueObjects/Entry.ts
Labels: type: bug

#4534 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#4486 feature: Add `group by` to collection view (Issue 3614)
  cypress/integration/view_filters_spec.js
  cypress/integration/view_groups_spec.js
  dev-test/backends/test/config.yml
  dev-test/config.yml
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/components/Collection/Collection.js
  packages/netlify-cms-core/src/components/Collection/CollectionControls.js
  packages/netlify-cms-core/src/components/Collection/ControlButton.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
  packages/netlify-cms-core/src/components/Collection/FilterControl.js
  packages/netlify-cms-core/src/components/Collection/GroupControl.js
  packages/netlify-cms-core/src/components/Collection/SortControl.js
  packages/netlify-cms-core/src/components/Collection/__tests__/Collection.spec.js
  packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/Collection.spec.js.snap
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-core/src/reducers/cursors.js
  packages/netlify-cms-core/src/reducers/entries.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-locales/src/en/index.js
Labels: type: feature

#4546 fix(docs-view-groups): add missing docs
  website/content/docs/configuration-options.md
Labels: type: bug

#4545 chore(widget-select): remove runtime validation for options
  packages/netlify-cms-widget-select/src/SelectControl.js
Labels: type: chore

#4565 fix(website): update slack link
  website/static/_redirects
Labels: type: bug

#4599 fix(widget-select): allow number value type
  dev-test/config.yml
  packages/netlify-cms-widget-select/src/schema.js
Labels: type: bug

#4610 fix(docs): re-add contributor style guide
  website/content/docs/writing-style-guide.md
Labels: type: bug

#4634 feat: i18n support for file collections - closes #4483
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/lib/__tests__/i18n.spec.js
  packages/netlify-cms-core/src/lib/i18n.ts
  website/content/docs/beta-features.md
Labels: type: feature

#4427 Feat/azure devops backend
  dev-test/backends/azure/config.yml
  dev-test/backends/azure/index.html
  packages/netlify-cms-app/package.json
  packages/netlify-cms-app/src/extensions.js
  packages/netlify-cms-backend-azure/README.md
  packages/netlify-cms-backend-azure/package.json
  packages/netlify-cms-backend-azure/src/API.ts
  packages/netlify-cms-backend-azure/src/AuthenticationPage.js
  packages/netlify-cms-backend-azure/src/implementation.ts
  packages/netlify-cms-backend-azure/src/index.ts
  packages/netlify-cms-backend-azure/webpack.config.js
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-lib-auth/src/implicit-oauth.js
  packages/netlify-cms-lib-util/src/API.ts
  packages/netlify-cms-lib-util/src/implementation.ts
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-locales/src/nl/index.js
  packages/netlify-cms-locales/src/tr/index.js
  packages/netlify-cms-ui-default/src/Icon/images/_index.js
  packages/netlify-cms-ui-default/src/Icon/images/azure.svg
  website/content/docs/azure-backend.md
Labels: type: feature

#4492 fix: list markdown widgets
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
Labels: type: bug

#4600 feat: added the referrer param for the workflow page
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
Labels: type: bug

#4612 fix(events): allow multiple event handlers to execute
  packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
  packages/netlify-cms-core/src/lib/registry.js
Labels: type: bug

#4607 fix(widget-string): fix cursor jumping to end of line
  packages/netlify-cms-widget-string/src/StringControl.js
Labels: type: bug

#4641 Fix the code highlights in docs/customization
  website/content/docs/customization.md
Labels: type: bug

#4639 fix(typings): add i18n support to typings
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4662 fix: added a TS type definition for local_backend schema field
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4650 feat(locales): add danish translation
  packages/netlify-cms-locales/src/da/index.js
  packages/netlify-cms-locales/src/index.js
Labels: type: feature

#4638 Update DOCS: Working with a Local Git Repository (take 2)
  website/content/docs/beta-features.md
Labels: type: content

#4640 fix(typings): discriminated types for widgets
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4663 fix(typings): add types for boolean and color widgets
  packages/netlify-cms-core/index.d.ts
Labels: type: bug
