Repository decaporg/decap-cms, pull requests merged in 2020-08, with the labels that each got.

#4095 Update Docs: Guides “nuxt”
  website/content/docs/nuxt.md
Labels: type: content

#4111 Add allow_add field (which is valid for list widgets)
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4117 Added ID-attribute to the Preview Pane Frame
  packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
Labels: type: feature

#4121 docs: replace outdated command
  website/content/docs/nuxt.md
Labels: type: bug

#4138 fix: persistent view style
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/components/Collection/Collection.js
  packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/Collection.spec.js.snap
  packages/netlify-cms-core/src/reducers/entries.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: bug

#4150 feat(preview-pane): pass iframe window and document instances as props
  packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
  website/content/docs/customization.md
Labels: type: feature

#4173 fix(locale): add missing translation strings for pt locale
  packages/netlify-cms-locales/src/pt/index.js
Labels: type: bug

#4178 Update Docs: Contributing “examples”
  website/content/docs/examples.md
  website/content/docs/start-with-a-template.md
  website/public/img/nextjs.svg
Labels: type: content

#4206 Fix SVGs when using local_backend
  packages/netlify-cms-backend-proxy/src/implementation.ts
Labels: type: bug

#4213 Update Docs: Guides “nuxt”
  website/content/docs/nuxt.md
Labels: type: content

#4214 chore: add labels and titles to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore

#4182 fix(widget-relation): set initial metadata value
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Labels: type: bug

#4146 Cms/kancer ezeroglu/netlify cms/docs fields/custom widgets
  website/content/docs/custom-widgets.md
  website/static/img/screen-shot-2020-08-20-at-14.36.26.png
Labels: type: content

#4172 fix: deprecate inconsistent config param case
  dev-test/backends/test/config.yml
  dev-test/backends/test/index.html
  dev-test/config.yml
  dev-test/index.html
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/components/Collection/__tests__/Collection.spec.js
  packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/Collection.spec.js.snap
  packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-widget-date/src/DateControl.js
  packages/netlify-cms-widget-datetime/src/DateTimeControl.js
  packages/netlify-cms-widget-datetime/src/schema.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/schema.js
  packages/netlify-cms-widget-number/src/NumberControl.js
  packages/netlify-cms-widget-number/src/__tests__/number.spec.js
  packages/netlify-cms-widget-number/src/schema.js
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
  packages/netlify-cms-widget-relation/src/schema.js
  website/content/docs/configuration-options.md
  website/content/docs/jekyll.md
  website/content/docs/widgets/date.md
  website/content/docs/widgets/datetime.md
  website/content/docs/widgets/markdown.md
  website/content/docs/widgets/number.md
  website/content/docs/widgets/relation.md
Labels: type: bug

#4241 chore(deps): lock file maintenance
  website/yarn.lock
  yarn.lock
Labels: type: chore
