Repository decaporg/decap-cms, pull requests merged in 2020-05, with the labels that each got.

#3697 Test(widgets-list): add tests
  jest.config.js
  packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
Labels: type: chore

#3687 Update Docs: Reference “configuration-options”
  website/content/docs/configuration-options.md
Labels: type: chore

#3616 feat(netlify-cms-widget-list): allow 'summary' field
  packages/netlify-cms-widget-list/package.json
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  website/content/docs/beta-features.md
  website/content/docs/widgets/list.md
Labels: type: feature

#3740 fix(date): allow default value to Date field
  packages/netlify-cms-widget-date/src/DateControl.js
Labels: type: bug

#3645 fix: delete new entry backup
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/components/Editor/Editor.js
Labels: type: bug

#3649 chore: timeout-requests closes #3605
  packages/netlify-cms-backend-bitbucket/src/git-lfs-client.ts
  packages/netlify-cms-backend-git-gateway/src/__tests__/GitHubAPI.spec.js
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.ts
  packages/netlify-cms-backend-github/src/__tests__/API.spec.js
  packages/netlify-cms-backend-github/src/__tests__/implementation.spec.js
  packages/netlify-cms-backend-github/src/implementation.tsx
  packages/netlify-cms-backend-proxy/src/implementation.ts
  packages/netlify-cms-core/src/integrations/providers/algolia/implementation.js
  packages/netlify-cms-core/src/integrations/providers/assetStore/implementation.js
  packages/netlify-cms-lib-util/src/unsentRequest.js
Labels: type: chore

#3745 fix(widget-code): change dynamic import to require
  packages/netlify-cms-widget-code/src/CodeControl.js
Labels: type: bug

#3721 feat: add pickerUtc option to datetime widget
  packages/netlify-cms-widget-datetime/src/DateTimeControl.js
  website/content/docs/widgets/datetime.md
Labels: type: feature

#3748 chore: add pr labeler
  .github/workflows/labeler.yml
Labels: type: chore

#3746 fix: allow setting an empty array as default for complex lists
  packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: bug

#3768 fix: clear fetch timeout on successful response
  packages/netlify-cms-lib-util/src/unsentRequest.js
Labels: type: bug

#3607 feat(widget-list): add hiding list content with minimize_collapsed option
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
  website/content/docs/widgets/list.md
Labels: type: feature

#3770 Improve Catalan translation
  packages/netlify-cms-locales/src/ca/index.js
Labels: type: bug

#3771 Add translation for "download" in mediaLibraryModal
  packages/netlify-cms-locales/src/es/index.js
Labels: type: bug

#3754 feat(widget-relation): target file collections
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
  website/content/docs/widgets/relation.md
Labels: type: feature

#3783 fix(widget-relation): fix displayFields default
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Labels: type: bug

#3786 Update Updates “releases”
  website/data/updates.yml
Labels: netlify-cms/pending_publish, type: content

#3789 chore: disable labeler on forked PRs
  .github/workflows/labeler.yml
Labels: type: chore

#3785 feat(lang): add norwegian
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/nb_no/index.js
  packages/netlify-cms-locales/src/nn_no/index.js
Labels: type: feature

#3741 feat: add filter to collection view
  cypress/integration/view_filters_spec.js
  cypress/support/commands.js
  dev-test/backends/test/config.yml
  dev-test/backends/test/index.html
  dev-test/config.yml
  dev-test/index.html
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/components/Collection/Collection.js
  packages/netlify-cms-core/src/components/Collection/CollectionControls.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
  packages/netlify-cms-core/src/components/Collection/FilterControl.js
  packages/netlify-cms-core/src/components/Collection/SortControl.js
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-core/src/reducers/entries.ts
  packages/netlify-cms-core/src/reducers/index.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-ui-default/src/Dropdown.js
  packages/netlify-cms-ui-default/src/index.js
  website/content/docs/configuration-options.md
Labels: type: feature

#3794 feat: allow author login/name to work in commit message templates #3793
  packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
  packages/netlify-cms-core/src/lib/formatters.ts
  website/content/docs/beta-features.md
Labels: type: feature

#3726 fix: Error UI improvements for nested lists/objects
  cypress/integration/editorial_workflow_spec_test_backend.js
  cypress/integration/field_validations_spec.js
  cypress/utils/constants.js
  cypress/utils/steps.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
  packages/netlify-cms-widget-object/src/ObjectControl.js
Labels: type: bug

#3801 chore(deps): update cypress
  package.json
  yarn.lock
Labels: type: chore

#3784 fix: Media Action Button closes #3639
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryActions.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryButtons.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryTop.js
Labels: type: bug

#3802 fix(locale): update translation strings for 'nl' locale
  packages/netlify-cms-locales/src/nl/index.js
Labels: type: chore

#3804 fix(config): validate unique fields names under the same level
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/netlify-cms-core/src/constants/configSchema.js
Labels: type: bug

#3805 feat: add allowed_hosts support in local_backend
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/netlify-cms-core/src/constants/configSchema.js
  website/content/docs/beta-features.md
Labels: type: feature

#3815 docs: update manual init docs
  website/content/docs/beta-features.md
Labels: type: bug

#3820 docs: add status badges
  README.md
Labels: type: chore

#3812 feat: add pre save/ post save hooks
  packages/netlify-cms-backend-test/src/implementation.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
  packages/netlify-cms-core/src/lib/registry.js
  packages/netlify-cms-core/src/types/immutable.ts
  packages/netlify-cms-lib-util/src/implementation.ts
  website/content/docs/beta-features.md
Labels: type: feature

#3826 Update Docs: Guides “nextjs”
  website/content/docs/nextjs.md
Labels: type: content
