Repository decaporg/decap-cms, pull requests merged in 2020-10, with the labels that each got.

#4391 Update Docs: Fix duplicate field name
  website/content/docs/jekyll.md
Labels: type: bug

#4392 Added missing German translations
  packages/netlify-cms-locales/src/de/index.js
Labels: type: bug

#4418 fix(locale): update zh_Hant translation
  packages/netlify-cms-locales/src/zh_Hant/index.js
Labels: type: bug

#4321 feat(test): add docs linter to PR workflow actions
  .github/workflows/docslint.yml
  .vale.ini
  website/content/docs/add-to-your-site.md
  website/content/docs/configuration-options.md
  website/content/docs/jekyll.md
  website/content/docs/widgets/image.md
  website/content/docs/widgets/list.md
  website/content/docs/widgets/map.md
  website/content/docs/widgets/markdown.md
  website/content/docs/widgets/object.md
  website/content/docs/widgets/relation.md
  website/content/docs/widgets/select.md
  website/package-lock.json
  website/src/writing-guide/styles/Avoid/Acronyms.yml
  website/src/writing-guide/styles/Avoid/Adverbs.yml
  website/src/writing-guide/styles/Avoid/Archaisms.yml
  website/src/writing-guide/styles/Avoid/Cliches.yml
  website/src/writing-guide/styles/Avoid/Hyperbole.yml
  website/src/writing-guide/styles/Avoid/Indirect.yml
  website/src/writing-guide/styles/Avoid/Jargon.yml
  website/src/writing-guide/styles/Avoid/Passive.yml
  website/src/writing-guide/styles/Avoid/Simplify.yml
  website/src/writing-guide/styles/README.md
  website/src/writing-guide/styles/README_proselint.md
  website/src/writing-guide/styles/Replace/Diacritical.yml
  website/src/writing-guide/styles/Replace/GenderBias.yml
  website/src/writing-guide/styles/Replace/Needless.yml
  website/src/writing-guide/styles/Replace/Nonwords.yml
  website/src/writing-guide/styles/Replace/Offensive.yml
  website/src/writing-guide/styles/Replace/Typography.yml
  website/src/writing-guide/styles/Replace/Variants.yml
  website/src/writing-guide/styles/archive/Paragraph.yml
  website/src/writing-guide/styles/archive/Sentence.yml
  website/src/writing-guide/vocab/accept.txt
  website/src/writing-guide/vocab/reject.txt
  website/src/writing-guide/writing-style-guide.md
  website/static/admin/config.yml
Labels: type: feature

#4421 Update 'th' locale
  packages/netlify-cms-locales/src/th/index.js
Labels: type: bug

#4423 #1289: allow to disable editor preview for all collections
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/constants/configSchema.js
  website/content/docs/configuration-options.md
Labels: type: feature

#4438 Add Eleventy Stater Boilerplate
  website/content/docs/examples.md
Labels: type: feature

#4414 fix: allow setting per-file editor preview
  packages/netlify-cms-core/src/components/Editor/EditorInterface.js
  packages/netlify-cms-core/src/reducers/collections.ts
Labels: type: feature

#4456 chore(docs): delete website/package-lock.json
  website/package-lock.json
Labels: type: chore

#4457 fix(docs): add missing docs about file preview config
  website/content/docs/configuration-options.md
Labels: type: bug

#4458 Fix 'th' locale translation
  packages/netlify-cms-locales/src/th/index.js
Labels: type: bug

#4432 fix(locale): remove hard coded strings
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-locales/src/zh_Hant/index.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/visual.js
Labels: type: bug

#4398 "summary" for object widget #4291
  packages/netlify-cms-widget-object/src/ObjectControl.js
  website/content/docs/widgets/object.md
Labels: type: feature

#4461 chore: use webpack serve instead of webpack-dev-server
  packages/netlify-cms/package.json
Labels: type: bug, type: chore

#4394 1480 min max
  packages/netlify-cms-lib-widgets/src/index.ts
  packages/netlify-cms-lib-widgets/src/validations.ts
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  packages/netlify-cms-widget-list/src/schema.js
  packages/netlify-cms-widget-select/package.json
  packages/netlify-cms-widget-select/src/SelectControl.js
  website/content/docs/widgets/list.md
Labels: type: feature

#4289 Issue 4174
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/actions/__tests__/editorialWorkflow.spec.js
  packages/netlify-cms-core/src/actions/editorialWorkflow.ts
  packages/netlify-cms-core/src/mediaLibrary.ts
  packages/netlify-cms-core/src/reducers/combinedReducer.js
  packages/netlify-cms-core/src/reducers/editorialWorkflow.ts
  packages/netlify-cms-core/src/redux/index.ts
  packages/netlify-cms-core/src/types/redux-optimist.d.ts
  yarn.lock
Labels: type: chore

#4490 chore(deps): update cypress
  package.json
  yarn.lock
Labels: type: chore

#4286 Update Docs: Intro “start-with-a-template”
  website/content/docs/examples.md
  website/content/docs/start-with-a-template.md
  website/static/img/nuxt.svg
Labels: type: content

#4396 Support filters for template strings #3677
  packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  website/content/docs/beta-features.md
Labels: type: feature

#4494 Update Docs: Guides “nuxt”
  website/content/docs/nuxt.md
Labels: type: content

#4464 Fixes #3807 by ensuring we don't attempt to split an empty string.
  packages/netlify-cms-widget-list/src/ListControl.js
Labels: type: bug

#4437 852 color widget
  dev-test/config.yml
  packages/netlify-cms-app/package.json
  packages/netlify-cms-app/src/extensions.js
  packages/netlify-cms-widget-color/CHANGELOG.md
  packages/netlify-cms-widget-color/README.md
  packages/netlify-cms-widget-color/package.json
  packages/netlify-cms-widget-color/src/ColorControl.js
  packages/netlify-cms-widget-color/src/ColorPreview.js
  packages/netlify-cms-widget-color/src/index.js
  packages/netlify-cms-widget-color/webpack.config.js
  website/content/docs/widgets/color.md
  yarn.lock
Labels: type: feature

#4496 fix(widget-color): rename to colorstring
  packages/netlify-cms-app/src/extensions.js
  packages/netlify-cms-widget-colorstring/CHANGELOG.md
  packages/netlify-cms-widget-colorstring/README.md
  packages/netlify-cms-widget-colorstring/package.json
  packages/netlify-cms-widget-colorstring/src/ColorControl.js
  packages/netlify-cms-widget-colorstring/src/ColorPreview.js
  packages/netlify-cms-widget-colorstring/src/index.js
  packages/netlify-cms-widget-colorstring/webpack.config.js
  yarn.lock
Labels: type: bug

#4465 feat: add add_to_top option to list widget
  packages/netlify-cms-widget-list/src/ListControl.js
  website/content/docs/widgets/list.md
Labels: type: feature

#4512 fix(deps): update color widget dependency
  packages/netlify-cms-app/package.json
  yarn.lock
Labels: type: bug
