Repository decaporg/decap-cms, pull requests merged in 2020-12, with the labels that each got.

#4678 fix(large-media): mark pointer files as binary
  packages/netlify-cms-backend-git-gateway/src/GitHubAPI.ts
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.ts
  packages/netlify-cms-backend-github/src/API.ts
Labels: type: bug

#4575 Adding a new Debugging section
  CONTRIBUTING.md
Labels: type: feature

#4698 fix(typings): migrate 'auth' state slice to TypeScript
  packages/netlify-cms-core/src/actions/auth.ts
  packages/netlify-cms-core/src/reducers/__tests__/auth.spec.js
  packages/netlify-cms-core/src/reducers/__tests__/auth.spec.ts
  packages/netlify-cms-core/src/reducers/auth.js
  packages/netlify-cms-core/src/reducers/auth.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#4705 Update Docs: Widgets “image”
  website/content/docs/widgets/image.md
Labels: type: content

#4699 Fixed sha256 import
  packages/netlify-cms-lib-util/src/getBlobSHA.ts
  packages/netlify-cms-lib-util/src/types/js-sha256.d.ts
Labels: type: bug

#4709 fix(typings): make 'status' state slice more typesafe
  packages/netlify-cms-core/src/actions/status.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/reducers/auth.ts
  packages/netlify-cms-core/src/reducers/status.ts
  packages/netlify-cms-core/src/types/immutable.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: bug

#4708 fix(i18n filtering): enable filtering when i18n is enabled
  packages/netlify-cms-core/src/backend.ts
Labels: type: bug

#4734 Update Docs: Guides “nextjs”
  website/content/docs/nextjs.md
Labels: type: content

#4727 Remove immutable from status and auth
  packages/netlify-cms-core/src/actions/status.ts
  packages/netlify-cms-core/src/components/App/App.js
  packages/netlify-cms-core/src/components/App/Header.js
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Editor/EditorInterface.js
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/reducers/__tests__/auth.spec.ts
  packages/netlify-cms-core/src/reducers/auth.ts
  packages/netlify-cms-core/src/reducers/status.ts
Labels: type: chore

#4740 refactor: remove immutable from medias state slice
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/actions/__tests__/media.spec.ts
  packages/netlify-cms-core/src/actions/media.ts
  packages/netlify-cms-core/src/reducers/__tests__/medias.spec.ts
  packages/netlify-cms-core/src/reducers/medias.ts
  packages/netlify-cms-core/src/types/redux.ts
  yarn.lock
Labels: type: chore

#4759 refactor: migrate history to TypeScript
  packages/netlify-cms-core/src/actions/collections.js
  packages/netlify-cms-core/src/actions/collections.ts
  packages/netlify-cms-core/src/lib/urlHelper.ts
  packages/netlify-cms-core/src/routing/__tests__/history.spec.ts
  packages/netlify-cms-core/src/routing/history.ts
Labels: type: chore

#4761 feat(locales): add Lithuanian translation
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/lt/index.js
Labels: type: feature
