Repository decaporg/decap-cms, pull requests merged in 2020-06, with the labels that each got.

#3835 Typo
  website/content/docs/jekyll.md
Labels: type: bug

#3832 fix: add missing type definitions
  packages/netlify-cms-core/index.d.ts
Labels: type: chore

#3838 chore: fix renovate config
  renovate.json
Labels: type: chore

#3839 chore: fix renovate config
  renovate.json
Labels: type: chore

#3843 fix: missing List import to netlify-cms-core index.d.ts
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#3847 Fix: handle token expiry
  packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js
  packages/netlify-cms-backend-bitbucket/src/implementation.ts
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-github/src/API.ts
  packages/netlify-cms-backend-github/src/implementation.tsx
  packages/netlify-cms-backend-gitlab/src/implementation.ts
  packages/netlify-cms-backend-proxy/src/implementation.ts
  packages/netlify-cms-backend-test/src/implementation.ts
  packages/netlify-cms-core/src/actions/auth.js
  packages/netlify-cms-core/src/actions/status.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/components/App/Header.js
  packages/netlify-cms-core/src/reducers/globalUI.js
  packages/netlify-cms-core/src/reducers/index.ts
  packages/netlify-cms-core/src/reducers/status.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-lib-util/src/AccessTokenError.ts
  packages/netlify-cms-lib-util/src/implementation.ts
  packages/netlify-cms-lib-util/src/index.ts
  packages/netlify-cms-locales/src/en/index.js
Labels: type: bug

#3850 fix(widget-relation): keep referenced field type when not using templates
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Labels: type: bug

#3813 fix(widget-markdown): don't strip new lines from text nodes
  packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/__snapshots__/parser.spec.js.snap
  packages/netlify-cms-widget-markdown/src/serializers/index.js
  packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js
Labels: type: bug

#3841 feat: add widgets schema validation
  packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-core/src/lib/registry.js
  packages/netlify-cms-widget-code/src/index.js
  packages/netlify-cms-widget-code/src/schema.js
  packages/netlify-cms-widget-datetime/src/index.js
  packages/netlify-cms-widget-datetime/src/schema.js
  packages/netlify-cms-widget-file/src/index.js
  packages/netlify-cms-widget-file/src/schema.js
  packages/netlify-cms-widget-image/src/index.js
  packages/netlify-cms-widget-image/src/schema.js
  packages/netlify-cms-widget-list/src/index.js
  packages/netlify-cms-widget-list/src/schema.js
  packages/netlify-cms-widget-map/src/index.js
  packages/netlify-cms-widget-map/src/schema.js
  packages/netlify-cms-widget-markdown/src/index.js
  packages/netlify-cms-widget-markdown/src/schema.js
  packages/netlify-cms-widget-number/src/index.js
  packages/netlify-cms-widget-number/src/schema.js
  packages/netlify-cms-widget-object/src/index.js
  packages/netlify-cms-widget-object/src/schema.js
  packages/netlify-cms-widget-relation/src/index.js
  packages/netlify-cms-widget-relation/src/schema.js
  packages/netlify-cms-widget-select/src/index.js
  packages/netlify-cms-widget-select/src/schema.js
  website/content/docs/custom-widgets.md
  website/content/docs/widgets/list.md
Labels: type: feature

#3855 Black lives matter
  website/data/notifications.yml
  website/src/components/header.js
  website/src/components/notification.js
  website/src/components/notifications.js
Labels: type: content

#3864 fix: update rehype-remark
  packages/netlify-cms-widget-markdown/package.json
  packages/netlify-cms-widget-markdown/src/serializers/__tests__/index.spec.js
  yarn.lock
Labels: type: bug

#3860 Update Docs: Guides “gatsby”
  website/content/docs/gatsby.md
Labels: type: content

#3863 Update Docs: Guides “hugo”
  website/content/docs/hugo.md
  website/static/admin/config.yml
  website/static/img/hugo_shortcode_gist.png
Labels: type: content

#3877 chore(deps): remove monaco editor unused deps
  packages/netlify-cms-widget-markdown/package.json
  yarn.lock
Labels: type: chore

#3878 build: increase webpack memory
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
  packages/netlify-cms-app/package.json
  packages/netlify-cms-core/package.json
  packages/netlify-cms/package.json
Labels: type: chore

#3879 Fix: handle branch names conflicts
  packages/netlify-cms-backend-bitbucket/src/API.ts
  packages/netlify-cms-backend-github/src/API.ts
  packages/netlify-cms-backend-github/src/GraphQLAPI.ts
  packages/netlify-cms-backend-gitlab/src/API.ts
  packages/netlify-cms-lib-util/src/API.ts
  packages/netlify-cms-lib-util/src/index.ts
Labels: type: bug

#3882 feat(backend-gitgateway): improve deploy preview visibility
  packages/netlify-cms-backend-bitbucket/src/API.ts
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-github/src/API.ts
  packages/netlify-cms-backend-gitlab/src/API.ts
Labels: type: feature

#3892 fix: don't rely on browser builtin css for CardsGrid margins
  packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
Labels: type: bug

#3890 feat(lang): add 'th' locale
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/th/index.js
Labels: type: feature

#3902 chore: fix PR labeler for forked PRs
  .github/workflows/labeler.yml
Labels: type: chore

#3903 fix: fix headings dropdown width
  packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
Labels: type: bug

#3889 feat: add backend status down indicator
  packages/netlify-cms-backend-bitbucket/src/implementation.ts
  packages/netlify-cms-backend-git-gateway/src/implementation.ts
  packages/netlify-cms-backend-github/src/implementation.tsx
  packages/netlify-cms-backend-gitlab/src/implementation.ts
  packages/netlify-cms-backend-proxy/src/implementation.ts
  packages/netlify-cms-backend-test/src/implementation.ts
  packages/netlify-cms-core/src/actions/status.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/reducers/status.ts
  packages/netlify-cms-lib-util/src/implementation.ts
  packages/netlify-cms-lib-util/src/unsentRequest.js
  packages/netlify-cms-locales/src/en/index.js
Labels: type: feature

#3906 Update Docs: Backends “gitlab-backend”
  website/content/docs/gitlab-backend.md
Labels: type: content

#3912 Revert "chore: fix PR labeler for forked PRs"
  .github/workflows/labeler.yml
Labels: type: chore

#3913 fix(schema): enforce files and collections names uniqueness
  packages/netlify-cms-core/src/constants/configSchema.js
Labels: type: bug

#3915 chore: remove pages collections from demo
  dev-test/config.yml
Labels: type: chore

#3921 fix(editor-media-lib): handle duplicate media folders
  packages/netlify-cms-core/src/reducers/collections.ts
Labels: type: bug

#3922 feat: pattern validation on blur event
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
Labels: type: feature

#3931 fix(widget-number): use number instead of integer in schema
  packages/netlify-cms-widget-number/src/schema.js
Labels: type: bug

#3910 Update Docs: Backends “bitbucket-backend”
  website/content/docs/bitbucket-backend.md
Labels: type: content

#3930 CI/ Simple workflow to create GitHub release
  .github/workflows/create-release.yml
Labels: type: chore

#3932 fix(backup): synchronize calls to localForage
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/backend.ts
Labels: type: bug

#3923 fix: only ISO date strings are parsed to Date objects
  packages/netlify-cms-core/src/formats/__tests__/yaml.spec.js
  packages/netlify-cms-core/src/formats/yaml.js
Labels: type: bug

#3943 Update Docs: Features “deploy-preview-links”
  website/content/docs/deploy-preview-links.md
Labels: netlify-cms/draft, type: content

#3947 Update Updates “notifications”
  website/data/notifications.yml
Labels: netlify-cms/pending_publish, type: content

#3948 fix: search file collections using top level file fields
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/backend.ts
Labels: type: bug

#3949 chore: fix dev site dates to iso format
  dev-test/backends/test/index.html
  dev-test/index.html
Labels: type: chore

#3926 header ui update closes #3263
  packages/netlify-cms-ui-default/src/AppBar/AppBar.jsx
  packages/netlify-cms-ui-default/src/SearchBar/SearchBar.jsx
  packages/netlify-cms-ui-default/src/SearchBar/index.js
  packages/netlify-cms-ui-default/src/SearchBar/story.jsx
Labels: type: feature

#3960 fix(editor): proper length check for history when going back in editor
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Labels: type: bug
