Repository decaporg/decap-cms, pull requests merged in 2021-11, with the labels that each got.

#5881 feat(locales): allow copying data from other locales (#5850)
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
  packages/netlify-cms-locales/src/de/index.js
  packages/netlify-cms-locales/src/en/index.js
Labels: type: feature

#5933 Update Docs: Configuration “configuration-options”
  website/content/docs/configuration-options.md
Labels: type: content

#5957 ci(workflow): add yarn' cache from setup-node action to 'e2e-with-cypress' job
  .github/workflows/nodejs.yml
Labels: type: chore

#5954 fix: Unformatted text in the widgets docs page
  website/content/docs/widgets.md
Labels: type: chore

#5903 feat(locales): add Hebrew translation
  packages/netlify-cms-locales/src/he/index.js
  packages/netlify-cms-locales/src/index.js
Labels: type: feature

#5979 Fix typos
  packages/netlify-cms-locales/src/hr/index.js
Labels: type: bug

#5981 Add missing `auth_type` to `CmsBackend` type
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5989 docs: add Nuxt 3 static files location
  website/content/docs/add-to-your-site.md
Labels: type: chore

#5992 Update Docs: Configuration “beta-features”
  website/content/docs/beta-features.md
Labels: type: content

#5993 Revert "chore(deps): lock file maintenance (#5987)"
  packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
  website/yarn.lock
  yarn.lock
Labels: type: chore
