Repository decaporg/decap-cms, pull requests merged in 2021-08, with the labels that each got.

#5595 Disable 'Save' button when there are no changes
  packages/netlify-cms-backend-git-gateway/src/__tests__/__snapshots__/AuthenticationPage.spec.js.snap
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/EditorToolbar.spec.js
  packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
  packages/netlify-cms-ui-default/src/styles.js
Labels: type: feature

#5679 fix(widget-list): add missing translations in widget list top bar
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
  packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
  packages/netlify-cms-widget-object/src/ObjectControl.js
Labels: type: bug

#5680 fix: overflow table on the docs page
  website/src/components/markdown.js
  website/src/components/sidebar-layout.js
Labels: type: bug

#5676 fix(markdown-widget): apply list item style on each block in a selection
  cypress/integration/markdown_widget_list_spec.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
Labels: type: bug

#5686 ref(locale-fr): Add FR translation for list buttons
  packages/netlify-cms-locales/src/fr/index.js
Labels: type: feature

#5698 style: indicate that disabled publish button is not clickable
  packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
Labels: type: feature

#5703 feat: update locale ja
  packages/netlify-cms-locales/src/ja/index.js
Labels: type: feature

#5705 docs(nextjs): add babel presets as dependencies
  website/content/docs/nextjs.md
Labels: type: feature

#5716 Make 'Now' button on DateTime widget consistent with 'Add' button on List widget
  packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js
  packages/netlify-cms-ui-default/src/styles.js
  packages/netlify-cms-widget-datetime/src/DateTimeControl.js
Labels: type: chore

#5597 fix(markdown-widget): support arbitrary component order
  packages/netlify-cms-core/src/valueObjects/EditorComponent.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js
  packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js
  packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js
  website/content/docs/custom-widgets.md
Labels: type: bug

#5722 fix(docs): fix typos in docs
  website/content/docs/beta-features.md
  website/content/docs/netlify-large-media.md
Labels: type: bug

#5725 Update Docs: Contributing “examples”
  website/content/docs/examples.md
Labels: type: content

#5728 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#5732 Update Docs: Intro “start-with-a-template”
  website/content/docs/start-with-a-template.md
Labels: type: content

#5731 remove/add copy to earlier paragraph
  website/content/docs/add-to-your-site.md
Labels: type: bug

#5748 update index.js pl
  packages/netlify-cms-locales/src/pl/index.js
Labels: type: feature
