Repository decaporg/decap-cms, pull requests merged in 2021-05, with the labels that each got.

#5316 feat: added react 17 as peer dependency in packages
  packages/netlify-cms-app/package.json
  packages/netlify-cms-backend-azure/package.json
  packages/netlify-cms-backend-bitbucket/package.json
  packages/netlify-cms-backend-git-gateway/package.json
  packages/netlify-cms-backend-github/package.json
  packages/netlify-cms-backend-gitlab/package.json
  packages/netlify-cms-backend-proxy/package.json
  packages/netlify-cms-backend-test/package.json
  packages/netlify-cms-core/package.json
  packages/netlify-cms-default-exports/package.json
  packages/netlify-cms-editor-component-image/package.json
  packages/netlify-cms-ui-default/package.json
  packages/netlify-cms-widget-boolean/package.json
  packages/netlify-cms-widget-code/package.json
  packages/netlify-cms-widget-colorstring/package.json
  packages/netlify-cms-widget-date/package.json
  packages/netlify-cms-widget-datetime/package.json
  packages/netlify-cms-widget-file/package.json
  packages/netlify-cms-widget-image/package.json
  packages/netlify-cms-widget-list/package.json
  packages/netlify-cms-widget-map/package.json
  packages/netlify-cms-widget-markdown/package.json
  packages/netlify-cms-widget-number/package.json
  packages/netlify-cms-widget-object/package.json
  packages/netlify-cms-widget-relation/package.json
  packages/netlify-cms-widget-select/package.json
  packages/netlify-cms-widget-string/package.json
  packages/netlify-cms-widget-text/package.json
Labels: type: feature

#5318 feat: add instruction for authenticating Netlify CMS users
  website/content/docs/jekyll.md
Labels: type: feature

#5320 Increase gitlabs' merge requests fetched to 100
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can change workflow status.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can create an entry.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can delete an entry.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can publish an editorial workflow entry.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can update an entry.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can update workflow status from within the editor.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can delete image from global media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can publish entry with image.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can save entry with image.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can upload image from entry media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can upload image from global media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__should not show draft entry image in global media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__should show published entry image in global media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__should show published entry image in grid view.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can change workflow status.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can create an entry.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can delete an entry.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can publish an editorial workflow entry.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can update an entry.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can update workflow status from within the editor.json
  cypress/fixtures/GitLab Backend Media Library - REST API__can publish entry with image.json
  cypress/fixtures/GitLab Backend Media Library - REST API__can save entry with image.json
  cypress/fixtures/GitLab Backend Media Library - REST API__should not show draft entry image in global media library.json
  cypress/fixtures/GitLab Backend Media Library - REST API__should show published entry image in global media library.json
  cypress/fixtures/GitLab Backend Media Library - REST API__should show published entry image in grid view.json
  packages/netlify-cms-backend-gitlab/src/API.ts
Labels: type: bug

#5341 fix(locale): add missing keys to 'sv' locale
  packages/netlify-cms-locales/src/sv/index.js
Labels: type: bug

#5351 fix(docs): image widget
  website/content/docs/widgets/image.md
Labels: type: content

#5349 Fix broken link
  website/content/docs/git-gateway-backend.md
Labels: type: bug

#5344 fixes: buttons using browser font-family, not the font-stack
  packages/netlify-cms-ui-default/src/styles.js
Labels: type: bug

#5353 fix(typing): type for CmsEventListener handler property
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5380 Revert "fix(deps): update dependency react-aria-menubutton to v7
  packages/netlify-cms-ui-default/package.json
  yarn.lock
Labels: type: bug

#5391 fix(config): allow empty public folder for collection,file,field
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.ts
Labels: type: bug

#5394 fix(deps): update react-select to v3
  packages/netlify-cms-widget-code/package.json
  packages/netlify-cms-widget-markdown/package.json
  packages/netlify-cms-widget-relation/package.json
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-select/package.json
  packages/netlify-cms-widget-select/src/SelectControl.js
  yarn.lock
Labels: type: bug

#5418 chore: run CI on latest Node.js
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
  .nvmrc
  website/.nvmrc
Labels: type: chore

#5421 Update Docs: Widgets “file”
  website/content/docs/widgets/file.md
Labels: type: content

#5443 chore: mark registerEventListener options as optional
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5445 chore: add hide option to CmsCollection type
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5442 fix spelling of the norwegian deleteEntry translation
  packages/netlify-cms-locales/src/nb_no/index.js
Labels: type: bug

#5447 chore: add document and window to PreviewTemplateComponentProps type
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5422 Fix some block style buttons not highlighted when clicking on the equivalent blocks in the editor
  packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js
Labels: type: bug

#5438 Convert absolute imports to relative ones
  .eslintrc.js
  babel.config.js
  package.json
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/actions/__tests__/editorialWorkflow.spec.js
  packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
  packages/netlify-cms-core/src/actions/__tests__/mediaLibrary.spec.js
  packages/netlify-cms-core/src/actions/collections.ts
  packages/netlify-cms-core/src/bootstrap.js
  packages/netlify-cms-core/src/components/App/App.js
  packages/netlify-cms-core/src/components/App/Header.js
  packages/netlify-cms-core/src/components/Collection/Collection.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesSearch.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
  packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
  packages/netlify-cms-core/src/components/Collection/Sidebar.js
  packages/netlify-cms-core/src/components/Collection/ViewStyleControl.js
  packages/netlify-cms-core/src/components/Collection/__tests__/Sidebar.spec.js
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
  packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/Editor.spec.js
  packages/netlify-cms-core/src/components/Editor/withWorkflow.js
  packages/netlify-cms-core/src/components/EditorWidgets/index.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryButtons.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js
  packages/netlify-cms-core/src/components/UI/SettingsDropdown.js
  packages/netlify-cms-core/src/components/UI/index.js
  packages/netlify-cms-core/src/components/Workflow/Workflow.js
  packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
  packages/netlify-cms-core/src/constants/configSchema.js
  packages/netlify-cms-core/src/index.js
  packages/netlify-cms-core/src/integrations/providers/algolia/implementation.js
  packages/netlify-cms-core/src/integrations/providers/assetStore/implementation.js
  packages/netlify-cms-core/src/lib/registry.js
  packages/netlify-cms-core/src/mediaLibrary.ts
  packages/netlify-cms-core/src/reducers/__tests__/entryDraft.spec.js
  packages/netlify-cms-core/src/reducers/__tests__/mediaLibrary.spec.js
  packages/netlify-cms-core/src/reducers/cursors.js
  packages/netlify-cms-core/src/reducers/entryDraft.js
  packages/netlify-cms-core/src/redux/index.ts
  packages/netlify-cms-core/src/routing/history.ts
  yarn.lock
Labels: type: chore

#5461 chore(deps): ignore some packages
  renovate.json
Labels: type: chore

#5342 feat(docs): add overview for integrating Netlify CSS with site generators
  website/content/docs/site-generator-overview.md
Labels: type: feature
