Repository decaporg/decap-cms, pull requests merged in 2021-02, with the labels that each got.

#4896 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: content

#4905 fix(backend-gitlab): increase rebase timeout
  packages/netlify-cms-backend-gitlab/src/API.ts
Labels: type: bug

#4910 fix: add missing displayURLs to state
  packages/netlify-cms-core/src/reducers/mediaLibrary.ts
Labels: type: bug

#4914 feat(media-library): add copy to clipboard, allow avif
  __mocks__/styleMock.js
  jest.config.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryButtons.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js
  packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryTop.js
  packages/netlify-cms-core/src/components/MediaLibrary/__tests__/MediaLibraryButtons.spec.js
  packages/netlify-cms-locales/src/en/index.js
Labels: type: feature

#4915 chore: migrate masterIssue to dependencyDashboard
  renovate.json
Labels: type: chore

#4919 chore: update slack link
  website/static/_redirects
Labels: type: chore

#4921 Add missing french translations to netlify-cms-locales package
  packages/netlify-cms-locales/src/fr/index.js
Labels: type: feature

#4922 chore(locale): update ru locale
  packages/netlify-cms-locales/src/ru/index.js
Labels: type: feature

#4909 fix: json FM ending with object parse error
  packages/netlify-cms-core/src/formats/__tests__/frontmatter.spec.js
  packages/netlify-cms-core/src/formats/frontmatter.js
Labels: type: bug

#4924 chore: improve cypress runs on forks
  .github/workflows/nodejs.yml
  cypress/run.js
  package.json
Labels: type: chore

#4893 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: content

#4846 refactor: mutate config in normalizeConfig and handleLocalBackend fns
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
Labels: type: chore

#4938 feat(locale): Make editor interface buttons translatable
  packages/netlify-cms-core/src/components/Editor/EditorInterface.js
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-locales/src/fr/index.js
Labels: type: feature

#4939 custom editorComponents name is cut by <ul> width #4894
  packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
Labels: type: bug

#4943 test: save cypress results as artifacts
  .github/workflows/nodejs.yml
Labels: type: chore

#4944 ref(locale-fr): change translation + missing '?'
  packages/netlify-cms-locales/src/fr/index.js
Labels: type: bug

#4940 refactor: remove ImmutableJS from applyDefaults function
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
Labels: type: chore

#4948 fix: convert config before passing to resolveBackend
  cypress/run.js
  packages/netlify-cms-core/src/actions/config.js
Labels: type: bug

#4951 test: fix cypress tests
  packages/netlify-cms-backend-bitbucket/src/API.ts
  packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
Labels: type: chore

#4950 refactor: convert config actions to TypeScript
  .eslintrc.js
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.ts
  packages/netlify-cms-core/src/types/global.d.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#4962 fix(typings): incorrect import in index.d.ts
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/constants/collectionTypes.ts
Labels: type: bug

#4969 Update Docs: Configuration “beta-features”
  website/content/docs/beta-features.md
Labels: type: content

#4971 Update Docs: Contributing “examples”
  website/content/docs/examples.md
Labels: type: content

#4985 Fixes user-facing config types in netlify-cms-core
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4989 fix(docs): update Hugo docs
  website/content/docs/hugo.md
Labels: type: bug

#4990 fix(core): typedef: globalStyles should not be required in CmsWidgetParam
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5012 chore: fix website build
  website/package.json
  website/yarn.lock
Labels: type: chore

#5015 Update Docs: Guides “nuxt” (quick typo fix)
  website/content/docs/nuxt.md
Labels: type: content

#5017 fix(core): ensure GridCardLink fills entire card
  packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
Labels: type: bug

#5024 chore: disable renovate rollbackPrs
  renovate.json
Labels: type: chore

#5028 docs: clarify i18n configuration for file collections
  website/content/docs/beta-features.md
Labels: type: bug
