Repository decaporg/decap-cms, pull requests merged in 2021-12, with the labels that each got.

#6010 fixed locales and added new ones.
  packages/netlify-cms-locales/src/tr/index.js
Labels: type: bug

#5994 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: content

#6018 feat: add generic type support for CmsWidget and CmsWidgetParam
  packages/netlify-cms-core/index.d.ts
Labels: type: chore

#6009 fix(csp): update ol and fix webpack global emit (#2138)
  packages/netlify-cms-widget-map/package.json
  packages/netlify-cms-widget-map/src/withMapControl.js
  yarn.lock
Labels: type: bug

#6038 chore: sync yarn
  yarn.lock
Labels: type: chore

#6053 chore: increase yarn network timeout
  .github/workflows/nodejs.yml
Labels: type: chore

#6069 refactor(netlify-cms-ui-default): use grayDark for button
  packages/netlify-cms-backend-git-gateway/src/__tests__/__snapshots__/AuthenticationPage.spec.js.snap
  packages/netlify-cms-ui-default/src/styles.js
Labels: type: bug

#6059 feat(backend-gitlab): initial GraphQL support
  packages/netlify-cms-backend-git-gateway/src/GitLabAPI.ts
  packages/netlify-cms-backend-gitlab/package.json
  packages/netlify-cms-backend-gitlab/src/API.ts
  packages/netlify-cms-backend-gitlab/src/implementation.ts
  packages/netlify-cms-backend-gitlab/src/queries.ts
  packages/netlify-cms-lib-util/src/implementation.ts
  website/content/docs/beta-features.md
Labels: type: feature

#6085 fix(docs-beta-features): fix Typo in comment
  website/content/docs/beta-features.md
Labels: type: bug
