Repository decaporg/decap-cms, pull requests merged in 2021-04, with the labels that each got.

#5104 Improve UX in Markdown editor - link editing and selected heading underline
  packages/netlify-cms-ui-default/src/Dropdown.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/Link.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/renderers.js
Labels: type: bug

#5087 Generate esm correctly
  babel.config.js
  packages/netlify-cms-app/package.json
  packages/netlify-cms/package.json
Labels: type: chore

#5207 fix(netlify-cms-package): remove module field
  packages/netlify-cms/package.json
Labels: type: bug

#5202 Update Docs: Workflow “open-authoring”
  website/content/docs/open-authoring.md
Labels: type: content

#5204 Add alwaysFork option for open authoring
  packages/netlify-cms-backend-github/src/implementation.tsx
  packages/netlify-cms-lib-util/src/implementation.ts
Labels: type: feature

#5030 fix: allow any default list as default value for list widgets
  packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
  packages/netlify-cms-widget-list/src/ListControl.js
  website/content/docs/widgets/list.md
Labels: type: feature

#5222 fix(locale-ca): update Catalan translation
  packages/netlify-cms-locales/src/ca/index.js
Labels: type: bug

#5157 Refactor search
  packages/netlify-cms-core/src/actions/__tests__/search.spec.js
  packages/netlify-cms-core/src/actions/search.ts
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesSearch.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/reducers/index.ts
  packages/netlify-cms-core/src/reducers/search.js
  packages/netlify-cms-core/src/reducers/search.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Labels: type: chore

#5224 chore: refactor globalUI
  packages/netlify-cms-core/src/components/App/App.js
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Workflow/Workflow.js
  packages/netlify-cms-core/src/reducers/__tests__/globalUI.js
  packages/netlify-cms-core/src/reducers/globalUI.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#5237 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: content

#5251 fix(docs-external-auth-client): use correct casing for GitHub, GitLab and TypeScript
  website/content/docs/external-oauth-clients.md
Labels: type: bug

#5238 feat: add min and max fields to relation widget (resolves #5026)
  packages/netlify-cms-locales/src/ca/index.js
  packages/netlify-cms-locales/src/da/index.js
  packages/netlify-cms-locales/src/de/index.js
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-locales/src/es/index.js
  packages/netlify-cms-locales/src/fr/index.js
  packages/netlify-cms-locales/src/hr/index.js
  packages/netlify-cms-locales/src/ja/index.js
  packages/netlify-cms-locales/src/ko/index.js
  packages/netlify-cms-locales/src/lt/index.js
  packages/netlify-cms-locales/src/nb_no/index.js
  packages/netlify-cms-locales/src/nl/index.js
  packages/netlify-cms-locales/src/nn_no/index.js
  packages/netlify-cms-locales/src/pl/index.js
  packages/netlify-cms-locales/src/pt/index.js
  packages/netlify-cms-locales/src/ru/index.js
  packages/netlify-cms-locales/src/sv/index.js
  packages/netlify-cms-locales/src/th/index.js
  packages/netlify-cms-locales/src/tr/index.js
  packages/netlify-cms-locales/src/vi/index.js
  packages/netlify-cms-locales/src/zh_Hant/index.js
  packages/netlify-cms-widget-relation/src/RelationControl.js
  packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
  packages/netlify-cms-widget-relation/src/schema.js
  website/content/docs/widgets/relation.md
Labels: type: feature

#5264 Update Docs: Account “github-backend”
  website/content/docs/github-backend.md
Labels: type: content

#5265 fix: add missing dependencies
  packages/netlify-cms-app/package.json
  packages/netlify-cms-core/package.json
Labels: type: bug

#5267 fix: add missing code codemirror deps
  packages/netlify-cms-app/package.json
Labels: type: bug

#5239 feat: Adds PKCE authentication for GitLab closes #5236
  packages/netlify-cms-backend-gitlab/src/AuthenticationPage.js
  packages/netlify-cms-lib-auth/src/implicit-oauth.js
  packages/netlify-cms-lib-auth/src/index.js
  packages/netlify-cms-lib-auth/src/pkce-oauth.js
  packages/netlify-cms-lib-auth/src/utils.js
  website/content/docs/external-oauth-clients.md
  website/content/docs/gitlab-backend.md
Labels: type: feature

#5271 fix: Revert "fix: generate esm correctly (#5087)"
  babel.config.js
  packages/netlify-cms-app/package.json
Labels: type: bug

#5257 docs: add netlify-cms-backend-* readme for developers
  packages/netlify-cms-backend-azure/README.md
  packages/netlify-cms-backend-bitbucket/README.md
  packages/netlify-cms-backend-git-gateway/README.md
  packages/netlify-cms-backend-github/README.md
  packages/netlify-cms-backend-gitlab/README.md
  packages/netlify-cms-backend-proxy/README.md
  packages/netlify-cms-backend-test/README.md
  packages/netlify-cms-lib-auth/README.md
  packages/netlify-cms-lib-util/README.md
Labels: type: feature

#5273 Migrate format helpers to ts
  packages/netlify-cms-core/src/formats/formats.ts
  packages/netlify-cms-core/src/formats/frontmatter.js
  packages/netlify-cms-core/src/formats/frontmatter.ts
  packages/netlify-cms-core/src/formats/helpers.ts
  packages/netlify-cms-core/src/formats/json.ts
  packages/netlify-cms-core/src/formats/toml.ts
  packages/netlify-cms-core/src/formats/yaml.ts
  packages/netlify-cms-core/src/types/redux.ts
  packages/netlify-cms-core/src/types/tomlify-j0.4.d.ts
Labels: type: feature

#5279 chore: remove dependabot config
  .dependabot/config.yml
Labels: type: chore

#5284 refactor: use plain object instead of enum
  packages/netlify-cms-core/src/formats/frontmatter.ts
Labels: type: chore

#5314 fix: Remove `Unpublish` UI button if collection has a `delete: false`. (#3887)
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Labels: type: bug

#5311 Fixing an issue with public_folder not working with absolute urls
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/lib/urlHelper.ts
  packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
  packages/netlify-cms-core/src/reducers/entries.ts
  website/content/docs/configuration-options.md
  yarn.lock
Labels: type: bug

#5313 Fix reference to `_includes/navigation.html` in jekyll.md
  website/content/docs/jekyll.md
Labels: type: bug
