Repository decaporg/decap-cms, pull requests merged in 2021-09, with the labels that each got.

#5796 chore(ci): pin Node.js version
  .github/workflows/nodejs.yml
Labels: type: chore

#5776 Remove svg checkmark from editor toolbar
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
Labels: type: bug

#5727 feat: pass strikethrough markdown for hint message on field
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  website/content/docs/widgets.md
  yarn.lock
Labels: type: feature

#5802 chore: use latest Node.js
  .github/workflows/nodejs.yml
Labels: type: chore

#5803 fix(deps): update react-datetime
  packages/netlify-cms-widget-date/package.json
  packages/netlify-cms-widget-datetime/package.json
  yarn.lock
Labels: type: bug

#5804 fix(widget-relation): don't invoke onChange if component is not mounted
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: type: bug

#5775 Fallback to title when overriding with empty or non-existant field
  packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js
  packages/netlify-cms-core/src/reducers/collections.ts
Labels: type: feature

#5810 Update Docs: Guides “jekyll”
  website/content/docs/jekyll.md
Labels: netlify-cms/draft, type: content

#5814 Update Contributing guide: Add more details to Debugging section
  CONTRIBUTING.md
Labels: type: feature

#5836 fix(translations): correct catalan locale
  packages/netlify-cms-locales/src/ca/index.js
Labels: type: bug

#5813 feat: change invoke CMS Events to throw Error
  packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
  packages/netlify-cms-core/src/lib/registry.js
Labels: type: feature

#5857 Update landing.yaml
  website/data/landing.yaml
Labels: type: bug
