Repository decaporg/decap-cms, pull requests merged in 2021-03, with the labels that each got.

#5052 Add branded README image
  README.md
  cms.png
Labels: type: feature

#5057 chore: update Gatsby to v3
  website/content/blog/implementing-a-jekyll-cms-in-3-days.md
  website/content/blog/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture.md
  website/content/blog/netlify-cms-now-supports-gitlab-as-a-backend.md
  website/content/docs/add-to-your-site.md
  website/content/docs/beta-features.md
  website/content/docs/middleman.md
  website/content/docs/netlify-large-media.md
  website/content/docs/nextjs.md
  website/content/docs/nuxt.md
  website/content/docs/open-authoring.md
  website/content/docs/writing-style-guide.md
  website/package.json
  website/public/img/nextjs.svg
  website/src/cms/cms.js
  website/src/components/blog-post-template.js
  website/src/components/docs-template.js
  website/src/components/features.js
  website/src/pages/blog.js
  website/src/templates/blog-post.js
  website/src/templates/doc-page.js
  website/static/admin/config.yml
  website/yarn.lock
Labels: type: chore

#5084 feat: update locale (ja)
  packages/netlify-cms-locales/src/ja/index.js
Labels: type: feature

#5090 chore: add missing next.js logo
  website/static/img/nextjs.svg
Labels: type: chore

#4960 refactor: remove immutable from 'config' state slice
  packages/netlify-cms-backend-gitlab/src/__tests__/gitlab.spec.js
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/__tests__/backend.spec.js
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
  packages/netlify-cms-core/src/actions/__tests__/mediaLibrary.spec.js
  packages/netlify-cms-core/src/actions/config.ts
  packages/netlify-cms-core/src/actions/editorialWorkflow.ts
  packages/netlify-cms-core/src/actions/entries.ts
  packages/netlify-cms-core/src/actions/mediaLibrary.ts
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/components/App/App.js
  packages/netlify-cms-core/src/components/App/Header.js
  packages/netlify-cms-core/src/components/Collection/Collection.js
  packages/netlify-cms-core/src/components/Collection/CollectionSearch.js
  packages/netlify-cms-core/src/components/Collection/Sidebar.js
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Editor/withWorkflow.js
  packages/netlify-cms-core/src/components/UI/ErrorBoundary.js
  packages/netlify-cms-core/src/components/UI/__tests__/ErrorBoundary.spec.js
  packages/netlify-cms-core/src/components/Workflow/Workflow.js
  packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
  packages/netlify-cms-core/src/constants/commitProps.ts
  packages/netlify-cms-core/src/constants/fieldInference.tsx
  packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
  packages/netlify-cms-core/src/lib/__tests__/urlHelper.spec.js
  packages/netlify-cms-core/src/lib/formatters.ts
  packages/netlify-cms-core/src/lib/urlHelper.ts
  packages/netlify-cms-core/src/mediaLibrary.ts
  packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js
  packages/netlify-cms-core/src/reducers/__tests__/config.spec.js
  packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
  packages/netlify-cms-core/src/reducers/__tests__/integrations.spec.ts
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-core/src/reducers/config.ts
  packages/netlify-cms-core/src/reducers/editorialWorkflow.ts
  packages/netlify-cms-core/src/reducers/entries.ts
  packages/netlify-cms-core/src/reducers/integrations.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#5085 fix: entry disappears from workflow screen on failing to merge pull request
  packages/netlify-cms-core/src/reducers/editorialWorkflow.ts
Labels: type: bug

#5095 fix: field based media_folder
  packages/netlify-cms-core/src/actions/entries.ts
Labels: type: bug

#5096 chore: remove connected-react-router
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/bootstrap.js
  packages/netlify-cms-core/src/reducers/combinedReducer.ts
  packages/netlify-cms-core/src/redux/index.ts
  yarn.lock
Labels: type: chore

#5100 fix: proper type for media library action
  packages/netlify-cms-core/src/actions/mediaLibrary.ts
  packages/netlify-cms-core/src/reducers/mediaLibrary.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#5131 test(e2e): use predictable branch name in proxy backend tests
  cypress/plugins/proxy.js
  dev-test/backends/proxy/config.yml
  package.json
  yarn.lock
Labels: type: chore

#5128 feat(locale): Added Romanian Locale
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/ro/index.js
Labels: type: feature

#5132 feat(locale): add zh_Hans locale
  packages/netlify-cms-locales/src/index.js
  packages/netlify-cms-locales/src/zh_Hans/index.js
Labels: type: chore

#5137 Fix webpack config in “custom-widgets”
  website/content/docs/custom-widgets.md
Labels: type: content

#5136 fix: i18n regex logic
  packages/netlify-cms-core/src/lib/__tests__/i18n.spec.js
  packages/netlify-cms-core/src/lib/i18n.ts
Labels: type: bug

#5135 chore: refactoring deploys
  packages/netlify-cms-core/src/actions/deploys.js
  packages/netlify-cms-core/src/actions/deploys.ts
  packages/netlify-cms-core/src/components/Editor/Editor.js
  packages/netlify-cms-core/src/components/Editor/EditorInterface.js
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/reducers/deploys.js
  packages/netlify-cms-core/src/reducers/deploys.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: chore

#5138 chore: don't run tests on tags
  .github/workflows/docslint.yml
  .github/workflows/nodejs.yml
Labels: type: chore

#5140 chore: always save tests artifacts
  .github/workflows/nodejs.yml
Labels: type: chore

#5127 #4897: fix code widget resize on focus bug
  packages/netlify-cms-widget-code/src/CodeControl.js
Labels: type: bug

#5155 chore: remove GitHub cache action
  .github/workflows/nodejs.yml
Labels: type: chore

#5187 test(e2e): add retries
  cypress.json
Labels: type: chore

#5159 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: bug

#5158 fix: #5143 added types for registerWidget()
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#5124 feat: #5082 add persistMedia function in widget props
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
Labels: type: feature

#5189 chore: update yarn file
  yarn.lock
Labels: type: chore

#5192 feat: update locale (nl)
  packages/netlify-cms-locales/src/nl/index.js
Labels: area: locales, type: feature
