Repository decaporg/decap-cms, pull requests merged in 2021-01, with the labels that each got.

#4799 chore: update slack invite link
  website/static/_redirects
Labels: type: chore

#4775 feat(locales): add Croatian translation
  packages/netlify-cms-locales/src/hr/index.js
  packages/netlify-cms-locales/src/index.js
Labels: type: feature

#4802 Skip creating a CI pipeline when rebasing the merge request
  packages/netlify-cms-backend-gitlab/src/API.ts
Labels: type: bug

#4801 Fixed translation issue of newButton (#4778)
  packages/netlify-cms-locales/src/de/index.js
Labels: type: bug

#4804 fix(typing): add `registerEventListener` to CMS interface
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#4805 refactor: use redux-devtools-extension package
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/redux/index.ts
  yarn.lock
Labels: type: chore

#4814 Update Docs: Collections “collection-types”
  website/content/docs/collection-types.md
Labels: type: bug, type: content

#4815 fix(locale): fix typos in es locales
  packages/netlify-cms-locales/src/es/index.js
Labels: type: bug

#4700 feat(widget-file): allow adding file from url
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-widget-file/src/withFileControl.js
Labels: type: feature

#4807 refactor: different config loading strategy
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/actions/__tests__/config.spec.js
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/bootstrap.js
  packages/netlify-cms-core/src/components/App/App.js
  packages/netlify-cms-core/src/reducers/config.ts
Labels: type: chore

#4840 fix: remove redundant ajv option
  packages/netlify-cms-core/src/constants/configSchema.js
Labels: type: bug

#4843 refactor: decouple config actions from auth actions
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/bootstrap.js
Labels: type: chore

#4849 fix(list-entries-integration): don't show commit date & author as default sort
  packages/netlify-cms-core/src/actions/config.js
  packages/netlify-cms-core/src/reducers/collections.ts
  packages/netlify-cms-core/src/reducers/integrations.ts
  packages/netlify-cms-core/src/types/redux.ts
Labels: type: bug

#4878 Update GitLab OAuth documentation
  website/content/docs/gitlab-backend.md
Labels: type: bug

#4880 fix(backend): allow calling 'json' again on 403 failure
  packages/netlify-cms-lib-util/src/API.ts
Labels: type: bug

#4856 Update Docs: Account “external-oauth-clients”
  website/content/docs/external-oauth-clients.md
Labels: type: content

#4881 chore: fix vale linting
  .github/workflows/docslint.yml
Labels: type: chore

#4879 Update Docs: Widgets “select”
  website/content/docs/widgets/select.md
Labels: type: content

#4887 chore: use Node.js version 15
  .github/workflows/labeler.yml
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
  .nvmrc
  package.json
  website/.nvmrc
  yarn.lock
Labels: type: chore

#4886 fix(security-markdown-widget): allow sanitization of preview content
  packages/netlify-cms-widget-markdown/package.json
  packages/netlify-cms-widget-markdown/src/MarkdownPreview.js
  packages/netlify-cms-widget-markdown/src/__tests__/__snapshots__/renderer.spec.js.snap
  packages/netlify-cms-widget-markdown/src/__tests__/renderer.spec.js
  website/content/docs/widgets/markdown.md
  yarn.lock
Labels: type: bug

#4857 feat(widget-image): enable images ordering
  packages/netlify-cms-widget-file/package.json
  packages/netlify-cms-widget-file/src/withFileControl.js
  yarn.lock
Labels: type: feature
