Repository decaporg/decap-cms, pull requests merged in 2021-07, with the labels that each got.

#5572 feat: image widget insert from url should be optional
  packages/netlify-cms-widget-file/src/withFileControl.js
  website/content/docs/widgets/file.md
  website/content/docs/widgets/image.md
Labels: type: feature

#5568 Feat: hide delete entry if open authoring
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/EditorToolbar.spec.js
  packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
Labels: type: feature

#5567 Feat: add hover tooltip
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/EditorToolbar.spec.js
  packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-ui-default/src/Icon/images/_index.js
  packages/netlify-cms-ui-default/src/Icon/images/info-circle.svg
Labels: type: feature

#5574 fixes #5557: modify status button to show the current status
  cypress/utils/steps.js
  packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
  packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
  packages/netlify-cms-core/src/reducers/entryDraft.js
  packages/netlify-cms-locales/src/bg/index.js
  packages/netlify-cms-locales/src/ca/index.js
  packages/netlify-cms-locales/src/cs/index.js
  packages/netlify-cms-locales/src/da/index.js
  packages/netlify-cms-locales/src/de/index.js
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-locales/src/es/index.js
  packages/netlify-cms-locales/src/fr/index.js
  packages/netlify-cms-locales/src/gr/index.js
  packages/netlify-cms-locales/src/hr/index.js
  packages/netlify-cms-locales/src/hu/index.js
  packages/netlify-cms-locales/src/it/index.js
  packages/netlify-cms-locales/src/ja/index.js
  packages/netlify-cms-locales/src/ko/index.js
  packages/netlify-cms-locales/src/lt/index.js
  packages/netlify-cms-locales/src/nb_no/index.js
  packages/netlify-cms-locales/src/nl/index.js
  packages/netlify-cms-locales/src/nn_no/index.js
  packages/netlify-cms-locales/src/pl/index.js
  packages/netlify-cms-locales/src/pt/index.js
  packages/netlify-cms-locales/src/ro/index.js
  packages/netlify-cms-locales/src/ru/index.js
  packages/netlify-cms-locales/src/sv/index.js
  packages/netlify-cms-locales/src/th/index.js
  packages/netlify-cms-locales/src/tr/index.js
  packages/netlify-cms-locales/src/uk/index.js
  packages/netlify-cms-locales/src/vi/index.js
  packages/netlify-cms-locales/src/zh_Hans/index.js
  packages/netlify-cms-locales/src/zh_Hant/index.js
Labels: type: bug

#5584 feat: pass markdown for hint message on field
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  website/content/docs/widgets.md
  yarn.lock
Labels: type: feature

#5591 docs(pr-template): add checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: feature

#5592 fix(list-control): better value validation
  packages/netlify-cms-widget-list/src/ListControl.js
Labels: type: bug

#5544 feat(list): Add heading for list widgets
  packages/netlify-cms-widget-list/src/ListControl.js
  packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
Labels: type: feature

#5616 test(e2e): only stop Cypress runner on last retry
  cypress/fixtures/BitBucket Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can change workflow status.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can create an entry.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can delete an entry.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can publish an editorial workflow entry.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can update an entry.json
  cypress/fixtures/BitBucket Backend Editorial Workflow__can update workflow status from within the editor.json
  cypress/fixtures/BitBucket Backend Media Library - Large Media__can publish entry with image.json
  cypress/fixtures/BitBucket Backend Media Library - Large Media__can save entry with image.json
  cypress/fixtures/BitBucket Backend Media Library - Large Media__should not show draft entry image in global media library.json
  cypress/fixtures/BitBucket Backend Media Library - Large Media__should show published entry image in global media library.json
  cypress/fixtures/BitBucket Backend Media Library - Large Media__should show published entry image in grid view.json
  cypress/fixtures/BitBucket Backend Media Library - REST API__can publish entry with image.json
  cypress/fixtures/BitBucket Backend Media Library - REST API__can save entry with image.json
  cypress/fixtures/BitBucket Backend Media Library - REST API__should not show draft entry image in global media library.json
  cypress/fixtures/BitBucket Backend Media Library - REST API__should show published entry image in global media library.json
  cypress/fixtures/BitBucket Backend Media Library - REST API__should show published entry image in grid view.json
  cypress/integration/common/spec_utils.js
  cypress/integration/editorial_workflow_spec_gitlab_backend.js
  cypress/integration/simple_workflow_spec_proxy_git_backend.js
Labels: type: chore

#5611 fix: add updated_at to graphql query
  cypress/fixtures/GitHub Backend Media Library - GraphQL API__can publish entry with image.json
  cypress/fixtures/GitHub Backend Media Library - GraphQL API__can save entry with image.json
  cypress/fixtures/GitHub Backend Media Library - GraphQL API__should not show draft entry image in global media library.json
  cypress/fixtures/GitHub Backend Media Library - GraphQL API__should show published entry image in global media library.json
  cypress/fixtures/GitHub Backend Media Library - GraphQL API__should show published entry image in grid view.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can change entry status from fork.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can create an entry on fork.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can create an entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can delete review entry from fork.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can publish an editorial workflow entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can return entry to draft and delete it.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can update a draft entry on fork.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API - Open Authoring__can update an entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can change status on and publish multiple entries.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can change workflow status.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can create an entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can delete an entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can publish an editorial workflow entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can update an entry.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can update workflow status from within the editor.json
  packages/netlify-cms-backend-github/src/GraphQLAPI.ts
  packages/netlify-cms-backend-github/src/fragments.ts
Labels: type: bug

#5620 Link to nested collections feature
  website/content/docs/collection-types.md
Labels: type: feature

#5550 Fix: Hitting Enter key in a list item doesn't create a new list item [NO CHANGING SCHEMA]
  cypress/integration/markdown_widget_list_spec.js
  cypress/integration/markdown_widget_quote_spec.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
Labels: type: bug

#5633 Allow registering remark plugins
  packages/netlify-cms-core/index.d.ts
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
  packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
  packages/netlify-cms-core/src/lib/registry.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CopyPasteVisual.js
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/visual.js
  packages/netlify-cms-widget-markdown/src/MarkdownPreview.js
  packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkPlugins.spec.js
  packages/netlify-cms-widget-markdown/src/serializers/index.js
  website/content/docs/beta-features.md
Labels: type: feature
