Repository decaporg/decap-cms, pull requests merged in 2022-02, with the labels that each got.

#6175 Update Docs: Account “github-backend”
  website/content/docs/github-backend.md
Labels: netlify-cms/pending_publish, type: content

#6179 ref(locale-hu): Add HU translation for list buttons
  packages/netlify-cms-locales/src/hu/index.js
Labels: type: bug, automerge

#6196 chore: sync yarn
  yarn.lock
Labels: type: chore

#6217 Update Docs: Intro “add-to-your-site”
  website/content/docs/add-to-your-site.md
Labels: type: content

#6218 fix(i18n): fix that unable to delete page with SINGLE_FILE i18n structure
  packages/netlify-cms-core/src/lib/__tests__/i18n.spec.js
  packages/netlify-cms-core/src/lib/i18n.ts
Labels: type: bug

#6244 chore: fix ci tests
  cypress/utils/steps.js
Labels: type: chore
