Repository decaporg/decap-cms, pull requests merged in 2022-04, with the labels that each got.

#6356 Update Docs: Contributing “examples”
  website/content/docs/examples.md
Labels: type: content

#6386 chore: enable lock file maintenance
  renovate.json
Labels: type: chore

#6390 chore(ci): add passing status checks when ignoring website changes
  .github/workflows/nodejs.yml
Labels: type: chore

#6392 chore: add checkout step
  .github/workflows/nodejs.yml
Labels: type: chore

#6299 fix(relation-widget): i18n options
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
  packages/netlify-cms-widget-object/src/ObjectControl.js
  packages/netlify-cms-widget-relation/src/RelationControl.js
Labels: area: extensions/widgets, area: i18n, type: bug, area: extensions/widgets/relation

#6281 fix: preview show error stack trace
  jest.config.js
  packages/netlify-cms-core/package.json
  packages/netlify-cms-core/src/components/UI/ErrorBoundary.js
  packages/netlify-cms-core/src/components/UI/__tests__/ErrorBoundary.spec.js
  packages/netlify-cms-core/src/components/UI/__tests__/__snapshots__/ErrorBoundary.spec.js.snap
  yarn.lock
Labels: type: bug, automerge

#5990 docs: add docusaurus guide
  website/content/docs/docusaurus.md
  website/static/img/screen-shot-2021-11-15-at-4.16.53-pm.png
  website/static/img/screen-shot-2021-11-16-at-1.34.18-PM.png
Labels: area: docs, type: feature, automerge
