Repository decaporg/decap-cms, pull requests merged in 2022-03, with the labels that each got.

#6278 chore: sync lock file
  yarn.lock
Labels: type: chore

#6282 Update Docs: Configuration “configuration-options”
  website/content/docs/configuration-options.md
Labels: type: content

#6308 feat(docs): add tips for running Jest CLI
  CONTRIBUTING.md
Labels: area: docs, type: feature, automerge

#6236 feat(image widget): media library gallery tools (#6087)
  packages/netlify-cms-core/src/actions/mediaLibrary.ts
  packages/netlify-cms-core/src/reducers/mediaLibrary.ts
  packages/netlify-cms-locales/src/en/index.js
  packages/netlify-cms-widget-file/src/withFileControl.js
Labels: type: feature

#6329 chore: sync lock file
  yarn.lock
Labels: type: chore

#6333 chore: replace deprecated String.prototype.substr()
  .eslintrc.js
  dev-test/backends/test/index.html
  dev-test/index.html
  package.json
  packages/netlify-cms-backend-azure/src/API.ts
  packages/netlify-cms-backend-github/src/API.ts
  packages/netlify-cms-backend-github/src/__tests__/API.spec.js
  packages/netlify-cms-core/src/backend.ts
  packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
  packages/netlify-cms-core/src/components/Collection/NestedCollection.js
  packages/netlify-cms-core/src/formats/frontmatter.ts
  packages/netlify-cms-core/src/lib/textHelper.js
  packages/netlify-cms-lib-util/src/APIUtils.ts
  packages/netlify-cms-lib-util/src/path.ts
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  packages/netlify-cms-proxy-server/src/middlewares/utils/fs.ts
  packages/netlify-cms-widget-file/src/withFileControl.js
  packages/netlify-cms-widget-markdown/src/serializers/slateRemark.js
  scripts/webpack.js
  yarn.lock
Labels: type: chore, automerge

#6352 chore: remove all .substring() usage
  cypress/plugins/bitbucket.js
  cypress/plugins/github.js
  cypress/plugins/gitlab.js
  cypress/plugins/proxy.js
  packages/netlify-cms-core/src/formats/frontmatter.ts
  packages/netlify-cms-core/src/lib/textHelper.js
  packages/netlify-cms-widget-file/src/withFileControl.js
  packages/netlify-cms-widget-markdown/src/serializers/slateRemark.js
Labels: type: chore

#6327 Update Docs: Intro “start-with-a-template”
  website/content/docs/start-with-a-template.md
  website/static/img/metalsmith.svg
Labels: type: feature
