Repository decaporg/decap-cms, pull requests merged in 2022-01, with the labels that each got.

#6089 chore: add missing `app_id` field to `CmsBackend` type
  packages/netlify-cms-core/index.d.ts
Labels: type: bug

#6100 chore: remove publish action
  .github/workflows/publish.yml
Labels: type: chore

#6135 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#6141 fix: remove redundant log from EditorControlPane
  packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
Labels: type: bug

#6134 feat: use keyboard shortcuts to insert bullet points
  packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
Labels: type: feature, automerge

#6105 feat: add truncate filter to summary tag
  packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js
  packages/netlify-cms-lib-widgets/src/stringTemplate.ts
  website/content/docs/beta-features.md
Labels: type: feature, automerge
