Repository decaporg/decap-cms, pull requests merged in 2023-10, with the labels that each got.

#6934 fix: change file-control default value to string
  packages/decap-cms-widget-file/src/withFileControl.js
Labels: type: bug

#6937 fix: consider i18n structure when building path regex
  packages/decap-cms-core/src/backend.ts
  packages/decap-cms-core/src/lib/i18n.ts
Labels: type: bug

#6947 feat: remove Vale docs linter
  .github/workflows/docslint.yml
  .vale.ini
  website/src/writing-guide/styles/Avoid/Acronyms.yml
  website/src/writing-guide/styles/Avoid/Adverbs.yml
  website/src/writing-guide/styles/Avoid/Archaisms.yml
  website/src/writing-guide/styles/Avoid/Cliches.yml
  website/src/writing-guide/styles/Avoid/Hyperbole.yml
  website/src/writing-guide/styles/Avoid/Indirect.yml
  website/src/writing-guide/styles/Avoid/Jargon.yml
  website/src/writing-guide/styles/Avoid/Passive.yml
  website/src/writing-guide/styles/Avoid/Simplify.yml
  website/src/writing-guide/styles/README.md
  website/src/writing-guide/styles/README_proselint.md
  website/src/writing-guide/styles/Replace/Diacritical.yml
  website/src/writing-guide/styles/Replace/GenderBias.yml
  website/src/writing-guide/styles/Replace/Needless.yml
  website/src/writing-guide/styles/Replace/Nonwords.yml
  website/src/writing-guide/styles/Replace/Offensive.yml
  website/src/writing-guide/styles/Replace/Typography.yml
  website/src/writing-guide/styles/Replace/Variants.yml
  website/src/writing-guide/styles/archive/Paragraph.yml
  website/src/writing-guide/styles/archive/Sentence.yml
  website/src/writing-guide/vocab/accept.txt
  website/src/writing-guide/vocab/reject.txt
  website/static/admin/config.yml
Labels: type: feature

#6808 feat(backend): add gitea backend
  dev-test/backends/gitea/config.yml
  dev-test/backends/gitea/index.html
  packages/decap-cms-app/src/extensions.js
  packages/decap-cms-backend-gitea/package.json
  packages/decap-cms-backend-gitea/src/API.ts
  packages/decap-cms-backend-gitea/src/AuthenticationPage.js
  packages/decap-cms-backend-gitea/src/__tests__/API.spec.js
  packages/decap-cms-backend-gitea/src/__tests__/implementation.spec.js
  packages/decap-cms-backend-gitea/src/implementation.tsx
  packages/decap-cms-backend-gitea/src/index.ts
  packages/decap-cms-backend-gitea/src/types.ts
  packages/decap-cms-backend-gitea/webpack.config.js
  packages/decap-cms-core/index.d.ts
  packages/decap-cms-core/src/types/redux.ts
  packages/decap-cms-lib-auth/src/pkce-oauth.js
  packages/decap-cms-locales/src/bg/index.js
  packages/decap-cms-locales/src/ca/index.js
  packages/decap-cms-locales/src/cs/index.js
  packages/decap-cms-locales/src/da/index.js
  packages/decap-cms-locales/src/de/index.js
  packages/decap-cms-locales/src/en/index.js
  packages/decap-cms-locales/src/es/index.js
  packages/decap-cms-locales/src/fa/index.js
  packages/decap-cms-locales/src/fr/index.js
  packages/decap-cms-locales/src/gr/index.js
  packages/decap-cms-locales/src/he/index.js
  packages/decap-cms-locales/src/hr/index.js
  packages/decap-cms-locales/src/it/index.js
  packages/decap-cms-locales/src/ja/index.js
  packages/decap-cms-locales/src/ko/index.js
  packages/decap-cms-locales/src/lt/index.js
  packages/decap-cms-locales/src/nb_no/index.js
  packages/decap-cms-locales/src/nl/index.js
  packages/decap-cms-locales/src/nn_no/index.js
  packages/decap-cms-locales/src/pl/index.js
  packages/decap-cms-locales/src/pt/index.js
  packages/decap-cms-locales/src/ro/index.js
  packages/decap-cms-locales/src/ru/index.js
  packages/decap-cms-locales/src/sv/index.js
  packages/decap-cms-locales/src/th/index.js
  packages/decap-cms-locales/src/tr/index.js
  packages/decap-cms-locales/src/ua/index.js
  packages/decap-cms-locales/src/vi/index.js
  packages/decap-cms-locales/src/zh_Hans/index.js
  packages/decap-cms-locales/src/zh_Hant/index.js
  packages/decap-cms-ui-default/src/Icon/images/_index.js
  packages/decap-cms-ui-default/src/Icon/images/gitea.svg
  website/content/docs/backends-overview.md
  website/content/docs/gitea-backend.md
Labels: area: extensions/backends, pinned

#6951 Update Docs: Media “netlify-large-media”
  website/content/docs/netlify-large-media.md
Labels: netlify-cms/pending_publish

#6953 Create Post “decap-3-1-0-beta-0”
  website/content/blog/decap-3-1-0-beta-0.md
  website/static/img/decap-3.1.0-beta.0.png
Labels: netlify-cms/pending_publish
