Repository decaporg/decap-cms, pull requests merged in 2023-11, with the labels that each got.

#6966 feat: add GTM
  website/gatsby-config.js
  website/package.json
  website/yarn.lock
Labels: type: feature

#6504 fix: used merge-upstream to sync fork & upstream
  packages/decap-cms-backend-github/src/implementation.tsx
  website/gatsby-config.js
Labels: pinned

#6969 Create Post “git-based-cms-definition-features-best-practices”
  website/content/blog/git-based-cms-definition-features-best-practices.md
  website/static/img/definition-features-best-practices.png
Labels: netlify-cms/pending_publish

#6977 feat(website): replace twiter image with image
  website/content/blog/decap-3-1-0-beta-0.md
  website/content/blog/decap-3.md
  website/content/blog/git-based-cms-definition-features-best-practices.md
  website/content/blog/github-discussions.md
  website/content/blog/introducing-decap.md
  website/content/blog/march-23-status-update.md
  website/content/blog/moving-to-discord.md
  website/content/blog/software-reviews-gold-medal-2023.md
  website/src/components/layout.js
  website/src/html.js
  website/src/templates/blog-post.js
  website/static/admin/config.yml
Labels: type: feature

#6981 Fix navigation blocker in editorial workflow
  cypress/e2e/common/media_library.js
  cypress/fixtures/Git Gateway (GitHub) Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/Git Gateway (GitHub) Backend Editorial Workflow__can update an entry.json
  cypress/fixtures/Git Gateway (GitHub) Backend Media Library - Large Media__can publish entry with image.json
  cypress/fixtures/Git Gateway (GitHub) Backend Media Library - Large Media__should not show draft entry image in global media library.json
  cypress/fixtures/Git Gateway (GitLab) Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/Git Gateway (GitLab) Backend Media Library - Large Media__can publish entry with image.json
  cypress/fixtures/GitLab Backend Editorial Workflow__can change status on and publish multiple entries.json
  cypress/fixtures/Github Backend Editorial Workflow - GraphQL API__can change status on and publish multiple entries.json
  cypress/fixtures/Github Backend Editorial Workflow - REST API__can change status on and publish multiple entries.json
  cypress/utils/steps.js
  packages/decap-cms-core/src/actions/editorialWorkflow.ts
  website/src/components/layout.js
Labels: type: bug
