Repository decaporg/decap-cms, pull requests merged in 2023-08, with the labels that each got.

#6489 Update cloudinary.md
  website/content/docs/cloudinary.md
Labels: status: stale

#6406 feat: changed minimum of 2 locales to minimum of 1
  packages/decap-cms-core/src/components/Editor/EditorInterface.js
  packages/decap-cms-core/src/constants/__tests__/configSchema.spec.js
  packages/decap-cms-core/src/constants/configSchema.js
Labels: pinned, type: feature

#6205 feat: register custom formats take 2
  packages/decap-cms-core/index.d.ts
  packages/decap-cms-core/src/constants/configSchema.js
  packages/decap-cms-core/src/formats/__tests__/formats.spec.js
  packages/decap-cms-core/src/formats/formats.ts
  packages/decap-cms-core/src/lib/__tests__/registry.spec.js
  packages/decap-cms-core/src/lib/registry.js
  packages/decap-cms-core/src/reducers/collections.ts
  packages/decap-cms-core/src/types/redux.ts
  website/content/docs/beta-features.md
Labels: pinned, type: feature

#6876 chore: remove react-toggled
  packages/decap-cms-core/src/components/Editor/EditorToolbar.js
  packages/decap-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
  packages/decap-cms-ui-default/package.json
  packages/decap-cms-ui-default/src/Toggle.js
  yarn.lock
Labels: type: chore

#6886 fix: update peer dependencies (decap packages)
  packages/decap-cms-backend-azure/package.json
  packages/decap-cms-backend-bitbucket/package.json
  packages/decap-cms-backend-git-gateway/package.json
  packages/decap-cms-backend-github/package.json
  packages/decap-cms-backend-gitlab/package.json
  packages/decap-cms-backend-proxy/package.json
  packages/decap-cms-backend-test/package.json
  packages/decap-cms-core/package.json
  packages/decap-cms-media-library-cloudinary/package.json
  packages/decap-cms-widget-boolean/package.json
  packages/decap-cms-widget-code/package.json
  packages/decap-cms-widget-colorstring/package.json
  packages/decap-cms-widget-date/package.json
  packages/decap-cms-widget-datetime/package.json
  packages/decap-cms-widget-file/package.json
  packages/decap-cms-widget-image/package.json
  packages/decap-cms-widget-list/package.json
  packages/decap-cms-widget-map/package.json
  packages/decap-cms-widget-markdown/package.json
  packages/decap-cms-widget-number/package.json
  packages/decap-cms-widget-object/package.json
  packages/decap-cms-widget-relation/package.json
  packages/decap-cms-widget-select/package.json
  packages/decap-cms-widget-string/package.json
  packages/decap-cms-widget-text/package.json
Labels: type: bug

#6494 ci(node.js): build and test with even versions of Node.js
  .github/workflows/nodejs.yml
Labels: area: dev experience, kind: enhancement, kind: experimental, pinned, type: feature

#6887 chore(node-ci): update machine count & node version
  .github/workflows/nodejs.yml
Labels: type: chore

#6897 fix: fill from locale error if undefined
  packages/decap-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
Labels: type: bug
